# This is a generated file. Not intended for manual editing.
version: "3.9"
services:
  ordering.api:
    build:
      context: "/home/saisumanth/Documents/newfolder/Dev Learning/BackendLearning/Projects/EShopMicroservice/src"
      dockerfile: "Services/Ordering/Ordering.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Ordering.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "ordering.api:dev"
    ports: []
    volumes:
    - "/home/saisumanth/Documents/newfolder/Dev Learning/BackendLearning/Projects/EShopMicroservice/src/Services/Ordering/Ordering.API:/app:rw"
    - "/home/saisumanth/Documents/newfolder/Dev Learning/BackendLearning/Projects/EShopMicroservice/src:/src:rw"
    - "/home/saisumanth/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
