version: '3.9'

services:
  catalogdb:
    container_name: catalogdb
    image: postgres:18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  basketdb:
    container_name: basketdb
    image: postgres:18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  orderdb:
    container_name: orderdb
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SwN12345678
    restart: always
    ports:
        - "1433:1433"
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'SwN12345678' -Q 'SELECT 1' -No" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  messagebroker:
    container_name: messagebroker
    image: rabbitmq:management
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  distributedcache:
    container_name: distributedcache
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  catalog.api:
    container_name: catalog.api
    image: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORT=8080
      - ASPNETCORE_HTTPS_PORT=8081
      - ConnectionStrings__CatalogDb=Host=catalogdb;Database=CatalogDb;Username=postgres;Password=postgres
    depends_on:
      catalogdb:
        condition: service_healthy
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ~/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/home/app/.aspnet/https:ro

  basket.api:
    container_name: basket.api
    image: basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORT=8080
      - ASPNETCORE_HTTPS_PORT=8081
      - ConnectionStrings__BasketDb=Host=basketdb;Database=BasketDb;Username=postgres;Password=postgres
      - Redis__ConnectionString=distributedcache:6379,abortConnect=false
      - GrpcSettings__DiscountUrl=https://discount.grpc:8081
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest

    depends_on:
      basketdb:
        condition: service_healthy
      distributedcache:
        condition: service_healthy
      messagebroker:
        condition: service_healthy
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ~/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/home/app/.aspnet/https:ro


  discount.grpc:
    container_name: discount.grpc
    image: discount.grpc
    build:
      context: .
      dockerfile: Discount.Grpc/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Test123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/aspnetapp.pfx
      - ConnectionStrings__Database=Data Source=/app/Data/discount.db
    ports:
        - "6002:8080"
        - "6062:8081"
    volumes:
      - ~/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/home/app/.aspnet/https:ro
      - ./Discount.Grpc/Data:/app/Data

  ordering.api:
    container_name: ordering.api
    image: ordering.api
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_URLS=http://+:8080   # ✅ disable HTTPS inside container
      - ConnectionStrings__Database=Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - FeatureManagement__OrderFullfilment=false
    depends_on:
      orderdb:
        condition: service_healthy
      messagebroker:
        condition: service_healthy
    ports:
      - "6003:8080"
      - "6063:8081"
    volumes:
      - ~/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/home/app/.aspnet/https:ro

  yarpapigateway:
    container_name: yarpapigateway
    image: yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Test123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/aspnetapp.pfx
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api
    ports:
      - "6004:8080"
      - "6064:8081"
    volumes:
      - ~/.aspnet/https:/home/app/.aspnet/https:ro

  shopping.web:
    container_name: shopping.web
    image: shopping.web
    build:
      context: .
      dockerfile: WebApps/Shopping.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ApiSettings__GatewayAddress=http://yarpapigateway:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Test123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/aspnetapp.pfx
    depends_on:
      - yarpapigateway
    ports:
      - "6005:8080"
      - "6065:8081"
    volumes:
      - ~/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/home/app/.aspnet/https:ro
volumes:
  postgres_catalog:
  postgres_basket:
  mssql_data:



